version: "3"
services:

  grpc-server:
    container_name: grpc-server
    build:
      context: ./server
      dockerfile: Dockerfile

  grpc-client:
    container_name: grpc-client
    build:
      context: ./client
      dockerfile: Dockerfile
    ports:
      - "3078:3078"